[2019-06-07 05:27:58 +0000] [14904] [INFO] Starting gunicorn 19.9.0
[2019-06-07 05:27:58 +0000] [14904] [INFO] Listening at: http://0.0.0.0:1346 (14904)
[2019-06-07 05:27:58 +0000] [14904] [INFO] Using worker: sync
[2019-06-07 05:27:58 +0000] [14907] [INFO] Booting worker with pid: 14907
[2019-06-07 05:27:58 +0000] [14907] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/monopoly/Envs/pi2_py3/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/monopoly/Envs/pi2_py3/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/monopoly/Envs/pi2_py3/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/monopoly/Envs/pi2_py3/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/monopoly/Envs/pi2_py3/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/monopoly/Envs/pi2_py3/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/monopoly/Envs/pi2_py3/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'app'
[2019-06-07 05:27:58 +0000] [14907] [INFO] Worker exiting (pid: 14907)
[2019-06-07 05:27:58 +0000] [14904] [INFO] Shutting down: Master
[2019-06-07 05:27:58 +0000] [14904] [INFO] Reason: Worker failed to boot.
